import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>رندترین</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center flex-col items-center">
        <h1 className="text-5xl font-extrabold text-center p-10">
          خرید سیم کارت در <span className="text-purple-purple-05">حراج</span>
        </h1>
        <small className="max-w-md text-center">
          رندترین مرجع رسمی همراه اول برای فروش سیمکارت به صورت حراج است. شما
          می‌توانید با پیشنهاد بالاترین قیمت، به سادگی سیم‌کارت مدنظرتان را
          بخرید.
        </small>
      </main>

      <footer></footer>
    </div>
  );
}
